import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Link from "next/link";
import MainDeck from "@/components/deck/MainDeck";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} grid-rows-layout grid min-h-[100vh]`}
      >
        <header>
          <div className="container py-4">
            <Link href="/">Home</Link>
          </div>
        </header>
        <main>{children}</main>
        <footer>
          <div className="container">footer</div>
        </footer>
        <MainDeck />
      </body>
    </html>
  );
}
