import MainDeck from "@/components/deck/MainDeck";
import { DeckStoreProvider } from "@/stores/deck-store-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} grid min-h-[100vh] grid-rows-layout`}
      >
        <DeckStoreProvider>
          <header>
            <div className="container py-4">
              <Link href="/">Home</Link>
            </div>
          </header>
          <main>{children}</main>
          <footer>
            <div className="container">footer</div>
          </footer>
          <MainDeck />
        </DeckStoreProvider>
      </body>
    </html>
  );
}
